WebUI/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogic;
using WebUI.Models;
using Models;

namespace WebUI.Controllers
{
    public class CustomerController : Controller
    {
        private IBL _BL;
        public CustomerController(IBL p_BL)
        {
            _BL = p_BL;
        }


        public IActionResult DisplayAllCustomers()
        {
            //convert Customer obj to CustomerVM obj
            return View(
                   _BL.GetAllCustomers()
                   .Select(cust => new CustomerVM(cust))
                   .ToList()
            );
        }

        //This action method only show the view
        public IActionResult CreateNewCustomer()
        {
            return View();
        }

        //only enact this method when there a post request
        [HttpPost]
        public IActionResult CreateNewCustomer(CustomerVM p_custVM)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    _BL.AddCustomer(new Customer
                        {
                            Fname = p_custVM.Fname,
                            Lname = p_custVM.Lname,
                            Address = p_custVM.Address,
                            City = p_custVM.City,
                            State = p_custVM.State,
                            Email = p_custVM.Email,
                            Phone = p_custVM.Phone
                        }   
                    );

                    // Go to the DisplayAllCustomers html of the Customer Controller
                    return RedirectToAction(nameof(DisplayAllCustomers));
                }
            }
            catch (Exception)
            {
                return View();
            }

            return View();
        }

        public IActionResult Edit(int p_id)
        {
            return View(new CustomerVM(_BL.GetACustomer(p_id)));
        }


        public IActionResult SearchForCustomer()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult SearchForCustomer(CustomerSearchVM p_searchVM)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    return RedirectToAction("DisplayListOfSearchedCustomer", new CustomerSearchVM {Criteria = p_searchVM.Criteria, Value = p_searchVM.Value});
                }
            }
            catch (Exception)
            {
                return View();
            }

            return View();
        }

        public IActionResult DisplayListOfSearchedCustomer(CustomerSearchVM p_searchVM)
        {
            List<Customer> listOfSearchedCustomer = _BL.SearchCustomers(p_searchVM.Criteria.ToString(), p_searchVM.Value);
            List<CustomerVM> listOfSearchedCustomerVM = new List<CustomerVM>();
            foreach (Customer c in listOfSearchedCustomer)
            {
                listOfSearchedCustomerVM.Add(new CustomerVM(c));
            }
            return View(listOfSearchedCustomerVM);
            //return View(p_searchVM);
        }
    }
}

WebUI/Controllers/ManagerPortalController.cs
using BusinessLogic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebUI.Models;
using Serilog;

namespace WebUI.Controllers
{
    public class ManagerPortalController : Controller
    {
        private IBL _BL;
        private static string productName = "";
        private static double productPrice = 0.00;
        public ManagerPortalController(IBL p_BL)
        {
            _BL = p_BL;
        }

        public IActionResult OpenManagerPortal()
        {
            return View();
        }

        [HttpPost]
        public IActionResult OpenManagerPortal(string p_password)
        {
            if(p_password == "1234")
            {
                return View(nameof(ManagerOption));
            }
            else
            {
                Log.Information("Manager Fail To Log In");
                ViewBag.Error = "Incorrect Password";
                return View();
            }
        }

        public IActionResult ManagerOption()
        {
            return View();
        }

        public IActionResult Customer()
        {
            return View();
        }


        public IActionResult CustomerDisplayAllCustomers()
        {
            try
            {
                //convert Customer obj to CustomerVM obj
                return View(
                       _BL.GetAllCustomers()
                       .Select(cust => new CustomerVM(cust))
                       .ToList()
                );
            }
            catch (Exception)
            {
                Log.Information("Fail To Get All Customer From DB");
                return View(nameof(Customer));
            }
        }

        //This action method only show the view
        public IActionResult CustomerCreateNewCustomer()
        {
            return View();
        }

        //only enact this method when there a post request
        [HttpPost]
        public IActionResult CustomerCreateNewCustomer(CustomerVM p_custVM)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    _BL.AddCustomer(new Customer
                    {
                        Fname = p_custVM.Fname.ToUpper(),
                        Lname = p_custVM.Lname.ToUpper(),
                        Address = p_custVM.Address.ToUpper(),
                        City = p_custVM.City.ToUpper(),
                        State = p_custVM.State.ToUpper(),
                        Email = p_custVM.Email,
                        Phone = p_custVM.Phone
                    }
                    );

                    // Go to the DisplayAllCustomers html of the Customer Controller
                    return RedirectToAction(nameof(OpenManagerPortal));
                }
            }
            catch (Exception)
            {
                Log.Information("Fail To Add Customer");
                ViewBag.Error = "Missing/Invalid Input --- Try Again";
                return View();
            }

            Log.Information("ModelState Invalid");
            ViewBag.Error = "Missing/Invalid Input --- Try Again";
            return View();
        }


        //public IActionResult CustomerEditCustomer(int p_id)
        //{
        //    return View(new CustomerVM(_BL.GetACustomer(p_id)));
        //}


        public IActionResult CustomerSearchForCustomer()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CustomerSearchForCustomer(CustomerSearchVM p_searchVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    return RedirectToAction("CustomerDisplayListOfSearchedCustomer", new CustomerSearchVM { Criteria = p_searchVM.Criteria, Value = p_searchVM.Value });
                }
            }
            catch (Exception)
            {
                return View();
            }

            return View();
        }

        public IActionResult CustomerDisplayListOfSearchedCustomer(CustomerSearchVM p_searchVM)
        {
            try
            {
                string value;
                if (p_searchVM.Criteria.ToString() == "email")
                {
                    value = p_searchVM.Value;
                }
                else
                {
                    value = p_searchVM.Value.ToUpper();
                }
                List<Customer> listOfSearchedCustomer = _BL.SearchCustomers(p_searchVM.Criteria.ToString(), value);
                List<CustomerVM> listOfSearchedCustomerVM = new List<CustomerVM>();
                foreach (Customer c in listOfSearchedCustomer)
                {
                    listOfSearchedCustomerVM.Add(new CustomerVM(c));
                }
                return View(listOfSearchedCustomerVM);
            }
            catch (Exception)
            {
                Log.Information("Fail To Search Customer");
                return View(nameof(CustomerSearchForCustomer));
            }
        }

        public IActionResult Order()
        {
            return View();
        }

        public IActionResult OrderDisplayAllstores()
        {
            try
            {
                return View(
                    _BL.GetAllStoreFronts()
                    .Select(sf => new StoreFrontVM(sf))
                    .ToList()
                );

            }
            catch (Exception)
            {
                Log.Information("Fail To Get All Store Fronts");
                return View(nameof(Order));
            }
        }

        public IActionResult OrderDisplayAStoreFrontOrders(int p_sfId, string sortOrder)
        {
            try
            {
                TempData["sfId"] = p_sfId;
                ViewBag.DateSortParm = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
                ViewBag.PriceSortParm = sortOrder == "price" ? "price_desc" : "price";


                IEnumerable<OrderVM> listOfStoreFrontOrders = _BL.GetAStoreFrontOrders(p_sfId).Select(order => new OrderVM(order)).ToList();

                switch (sortOrder)
                {
                    case "price":
                        listOfStoreFrontOrders = listOfStoreFrontOrders.OrderBy(o => o.TotalPrice);
                        break;
                    case "price_desc":
                        listOfStoreFrontOrders = listOfStoreFrontOrders.OrderByDescending(o => o.TotalPrice);
                        break;

                    case "date_desc":
                        listOfStoreFrontOrders = listOfStoreFrontOrders.OrderByDescending(o => o.Date);
                        break;
                    default:
                        listOfStoreFrontOrders = listOfStoreFrontOrders.OrderBy(o => o.Date);
                        break;
                }

                return View(listOfStoreFrontOrders);
            }
            catch (Exception)
            {
                Log.Information("Fail To Sort Order");
                return View(nameof(Order));
            }
        }

        public IActionResult OrderDisplayOrderDetail(int p_orderId)
        {
            try
            {
                List<LineItemVM> listOfAnOrderLineItems = _BL.GetAnOrderLineItems(p_orderId).Select(li => new LineItemVM(li)).ToList();
                List<Product> listOfProducts = _BL.GetAllProducts();
                foreach (LineItemVM liVM in listOfAnOrderLineItems)
                {
                    foreach (Product p in listOfProducts)
                    {
                        if (liVM.ProductId == p.Id)
                        {
                            liVM.ProductName = p.Name;
                            liVM.ProductPrice = p.Price;
                        }
                    }
                }
                return View(listOfAnOrderLineItems);
            }
            catch (Exception)
            {
                Log.Information("Fail To Display Order Detail");
                return View(nameof(Order));
            }
        }
        public IActionResult Inventory()
        {
            return View();
        }

        public IActionResult InventoryDisplayAllstores()
        {
            try
            {
                return View(
                    _BL.GetAllStoreFronts()
                    .Select(sf => new StoreFrontVM(sf))
                    .ToList()
                );
            }
            catch (Exception)
            {
                Log.Information("Fail To Get All Store Fronts");
                return View(nameof(Inventory));
            }
        }

        public IActionResult InventoryDisplayAStoreInventory(int p_sfId)
        {
            try
            {
                TempData["sfId"] = p_sfId;
                ViewBag.Name = _BL.GetAStore(p_sfId).Name;
                List<Inventory> listOfTheStoreInventory = _BL.GetAStoreInventory(p_sfId);
                List<Product> listOfAllProducts = _BL.GetAllProducts();
                List<TheStoreInventoryVM> listOfTheStoreInventoryVM = new List<TheStoreInventoryVM>();
                foreach (Inventory inv in listOfTheStoreInventory)
                {
                    TheStoreInventoryVM inventoryVM = new TheStoreInventoryVM();
                    inventoryVM.Id = inv.Id;
                    inventoryVM.StoreFrontId = inv.StoreFrontId;
                    inventoryVM.Quantity = inv.Quantity;
                    foreach (Product p in listOfAllProducts)
                    {
                        if (inv.ProductId == p.Id)
                        {
                            inventoryVM.ProductId = p.Id;
                            inventoryVM.ProductName = p.Name;
                            inventoryVM.ProductPrice = p.Price;
                        }
                    }
                    listOfTheStoreInventoryVM.Add(inventoryVM);
                }
                return View(listOfTheStoreInventoryVM);

WebUI/Views/ManagerPortal/CreateNewCustomer.cshtml
@model WebUI.Models.CustomerVM
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>Add New Customer</h1>

    <div>
        <form asp-action="CreateNewCustomer">
            <div class="mb-3">
                <label asp-for="Fname" class="form-label">First Name</label>
                <input asp-for="Fname" type="text" class="form-control">
                <span asp-validation-for="Fname" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Lname" class="form-label">Last Name</label>
                <input asp-for="Lname" type="text" class="form-control">
                <span asp-validation-for="Lname" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Address" class="form-label">Address</label>
                <input asp-for="Address" type="text" class="form-control">
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="City" class="form-label">City</label>
                <input asp-for="City" type="text" class="form-control">
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="State" class="form-label">State</label>
                <input asp-for="State" type="text" class="form-control">
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input asp-for="Email" type="text" class="form-control">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Phone" class="form-label">Phone</label>
                <input asp-for="Phone" type="number" min="0" class="form-control">
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <a asp-controller="ManagerPortal" asp-action="OpenManagerPortal" class="btn btn-danger" style="position:relative; top:10px; width:77px;">Back</a>
</body>
</html>

WebUI/Views/ManagerPortal/Customer.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1 style="text-align:center">Customer</h1>
    <table>
        <tbody>
            <tr>
                <td>
                    <a type="button" class="btn btn-secondary" asp-controller="ManagerPortal" asp-action="CustomerCreateNewCustomer">Create New Customer</a>
                </td>
            </tr>
            <tr>
                <td>
                    <a type="button" class="btn btn-secondary" asp-controller="ManagerPortal" asp-action="CustomerDisplayAllCustomers">Display All Customers</a>
                </td>
            </tr>
            <tr>
                <td>
                    <a type="button" class="btn btn-secondary" asp-controller="ManagerPortal" asp-action="CustomerSearchForCustomer">Search For Customers</a>
                </td>
            </tr>
            <tr>
                <td>
                    <a asp-controller="ManagerPortal" asp-action="ManagerOption" class="btn btn-danger">Back</a>
                </td>
            </tr>
        </tbody>
    </table>
</body>
</html>

WebUI/Views/ManagerPortal/CustomerCreateNewCustomer.cshtml
@model WebUI.Models.CustomerVM
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>Add New Customer</h1>

    <div>
        <form asp-action="CustomerCreateNewCustomer">
            @{ if (ViewBag.Error != null)
            {
            <div class="mb-3" style="color:red">@ViewBag.Error</div> 
            } 
            }
            <div class="mb-3">
                <label asp-for="Fname" class="form-label">First Name</label>
                <input asp-for="Fname" type="text" class="form-control">
                <span asp-validation-for="Fname" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Lname" class="form-label">Last Name</label>
                <input asp-for="Lname" type="text" class="form-control">
                <span asp-validation-for="Lname" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Address" class="form-label">Address</label>
                <input asp-for="Address" type="text" class="form-control">
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="City" class="form-label">City</label>
                <input asp-for="City" type="text" class="form-control">
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="State" class="form-label">State</label>
                <input asp-for="State" type="text" class="form-control">
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input asp-for="Email" type="text" class="form-control">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Phone" class="form-label">Phone</label>
                <input asp-for="Phone" type="number" min="0" class="form-control">
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <a asp-controller="ManagerPortal" asp-action="Customer" class="btn btn-danger" style="position:relative; top:10px; width:77px;">Back</a>
</body>
</html>

WebUI/Views/ManagerPortal/CustomerDisplayAllCustomers.cshtml
@model IEnumerable<WebUI.Models.CustomerVM>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>List Of All Customers</h1>

    @*<button type="button" class="btn btn-secondary">Search</button>
        <a class="btn btn-secondary" asp-action="CreateNewCustomer">Add</a>*@

    <table class="table table-striped">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Email</th>
                <th>Phone</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Fname)</td>
                    <td>@Html.DisplayFor(modelItem => item.Lname)</td>
                    <td>@Html.DisplayFor(modelItem => item.Address)</td>
                    <td>@Html.DisplayFor(modelItem => item.City)</td>
                    <td>@Html.DisplayFor(modelItem => item.State)</td>
                    <td style="width: 100px">@Html.DisplayFor(modelItem => item.Email)</td>
                    <td>@String.Format("{0:(###) ###-####}", long.Parse(item.Phone))</td>
                    @*<td>
                        @Html.ActionLink("Edit", "CustomerEditCustomer", new { p_id = item.Id }, new { @style = "color:white", @class = "btn btn-secondary" })
                    </td>*@
                </tr>
            }
        </tbody>
    </table>
    <a asp-controller="ManagerPortal" asp-action="Customer" class="btn btn-danger" style="position:relative; top:10px; width:77px;">Back</a>

</body>
</html>

WebUI/Views/ManagerPortal/CustomerSearchForCustomer.cshtml
@model CustomerSearchVM

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>Search For Customer</h1>

    <form asp-action="CustomerSearchForCustomer">
        <div class="mb-3">
            <label asp-for="Criteria" class="form-label">Search Criteria</label>
            @Html.DropDownListFor(cust => cust.Criteria, new SelectList(Enum.GetValues(typeof(SearchCriteria))))
        </div>
        <div class="mb-3">
            <label asp-for="Value" class="form-label">Search Value</label>
            <input asp-for="Value" type="text" class="form-control">
            <span asp-validation-for="Value" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <a asp-controller="ManagerPortal" asp-action="Customer" class="btn btn-danger" style="position:relative; top:10px; width:77px;">Back</a>

</body>
</html>

WebUI/Views/ManagerPortal/DisplayAllCustomers.cshtml
@model IEnumerable<WebUI.Models.CustomerVM>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>List Of All Customers</h1>

    @*<button type="button" class="btn btn-secondary">Search</button>
        <a class="btn btn-secondary" asp-action="CreateNewCustomer">Add</a>*@

    <table class="table table-striped">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Email</th>
                <th>Phone</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Fname)</td>
                    <td>@Html.DisplayFor(modelItem => item.Lname)</td>
                    <td>@Html.DisplayFor(modelItem => item.Address)</td>
                    <td>@Html.DisplayFor(modelItem => item.City)</td>
                    <td>@Html.DisplayFor(modelItem => item.State)</td>
                    <td>@Html.DisplayFor(modelItem => item.Email)</td>
                    <td>@Html.DisplayFor(modelItem => item.Phone)</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { p_id = item.Id }, new { @style = "color:white", @class = "btn btn-secondary" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-controller="ManagerPortal" asp-action="OpenManagerPortal" class="btn btn-danger" style="position:relative; top:10px; width:77px;">Back</a>

</body>
</html>

WebUI/Views/ManagerPortal/DisplayListOfSearchedCustomer.cshtml
@model IEnumerable<CustomerVM>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>List Of Searched Customers</h1>


    <table class="table table-striped">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Email</th>
                <th>Phone</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Fname)</td>
                    <td>@Html.DisplayFor(modelItem => item.Lname)</td>
                    <td>@Html.DisplayFor(modelItem => item.Address)</td>
                    <td>@Html.DisplayFor(modelItem => item.City)</td>
                    <td>@Html.DisplayFor(modelItem => item.State)</td>
                    <td>@Html.DisplayFor(modelItem => item.Email)</td>
                    <td>@Html.DisplayFor(modelItem => item.Phone)</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { p_id = item.Id }, new { @style = "color:white", @class = "btn btn-secondary" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-controller="ManagerPortal" asp-action="OpenManagerPortal" class="btn btn-danger" style="position:relative; top:10px; width:77px;">Back</a>
</body>
</html>

WebUI/Views/ManagerPortal/ManagerOption.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1 style="text-align:center">Manager Options</h1>
    <table>
        <tbody>
            <tr>
                <td>
                    <a type="button" class="btn btn-secondary" asp-controller="ManagerPortal" asp-action="Customer">Customer</a>
                </td>
            </tr>
            <tr>
                <td>
                    <a type="button" class="btn btn-secondary" asp-controller="ManagerPortal" asp-action="Inventory">Inventory</a>
                </td>
            </tr>
            <tr>
                <td>
                    <a type="button" class="btn btn-secondary" asp-controller="ManagerPortal" asp-action="Order">Order</a>
                </td>
            </tr>
            <tr>
                <td>
                    <a asp-controller="ManagerPortal" asp-action="OpenManagerPortal" class="btn btn-danger">Log Out</a>
                </td>
            </tr>
        </tbody>
    </table>


</body>
</html>

WebUI/Views/ManagerPortal/OrderDisplayAStoreFrontOrders.cshtml
@model IEnumerable<OrderVM>
@{ 
    int sfId = (int)TempData["sfId"];
    TempData.Keep("sfId");
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1 style="text-align:center;">Order History</h1>
    @{ if (Model.Count() > 0)
        {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Order Id</th>
                        <th>Customer Id</th>
                        <th>@Html.ActionLink("Total Price", "OrderDisplayAStoreFrontOrders", new { p_sfId = sfId, sortOrder = ViewBag.PriceSortParm })</th>
                        <th>@Html.ActionLink("Date of Sale", "OrderDisplayAStoreFrontOrders", new { p_sfId = sfId, sortOrder = ViewBag.DateSortParm })</th>
                        <th>Detail</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.CustomerId</td>
                            <td>@item.TotalPrice.ToString("C")</td>
                            <td>@item.Date</td>
                            <td>
                                @Html.ActionLink("Display", "OrderDisplayOrderDetail", new { p_orderId = item.Id }, new { @style = "color:white", @class = "btn btn-secondary" })
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        }
        else
        {
            <h2>Store Front Has No Order History</h2>
        }
    }
    <a asp-controller="ManagerPortal" asp-action="OrderDisplayAllStores" class="btn btn-danger" style="position:relative; top:10px; width:77px;">Back</a>
</body>
</html>

WebUI/Views/ManagerPortal/OrderDisplayAllStores.cshtml
@model IEnumerable<StoreFrontVM>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>List Of Stores</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Store Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Order History</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.Address)</td>
                    <td>@Html.DisplayFor(modelItem => item.City)</td>
                    <td>@Html.DisplayFor(modelItem => item.State)</td>
                    <td>
                        @Html.ActionLink("Display", "OrderDisplayAStoreFrontOrders", new { p_sfId = item.Id }, new { @style = "color:white", @class = "btn btn-secondary" })
                    </td>
                </tr>            
             }
        </tbody>
    </table>
    <a asp-controller="ManagerPortal" asp-action="Order" class="btn btn-danger" style="position:relative; top:10px; width:77px;">Back</a>
</body>
</html>

WebUI/Views/ManagerPortal/OrderDisplayOrderDetail.cshtml
@model IEnumerable<LineItemVM>
@{
    double total = 0.0;
    int sfId = (int)TempData["sfId"];
    TempData.Keep("sfId");
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>Order Detail:</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Product ID</th>
                <th>Product Name</th>
                <th>Product Price</th>
                <th>Purchased Quantity</th>
                <th>Line Totals</th>

            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ProductId</td>
                        <td>@item.ProductName</td>
                        <td>@item.ProductPrice.ToString("C")</td>
                        <td>@item.Quantity</td>
                        @{
                            double subTotal = item.ProductPrice * item.Quantity;
                            total += subTotal;
                        }
                        <td>@subTotal.ToString("C")</td>

                    </tr>
                }
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">Total</td>
                <td>@total.ToString("C")</td>
            </tr>
        </tfoot>
    </table>

    @*@Html.ActionLink("Back", "DisplayAStoreFrontOrders", new { p_sfId =  sfId}, new { @style = "color:white; position:relative; top:10px; width:77px;", @class = "btn btn-secondary" })*@
    <a asp-action="OrderDisplayAStoreFrontOrders" asp-controller="ManagerPortal" asp-route-p_sfId="@sfId" style = "color:white; position:relative; top:10px; width:77px;" class = "btn btn-danger" >Back</a>
</body>
</html>