WebUI/Controllers/CustomerPortalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models;
using WebUI.Models;
using Serilog;

namespace WebUI.Controllers
{
    public class CustomerPortalController : Controller
    {
        private IBL _BL;
        private static List<LineItemVM> shoppingCart = new List<LineItemVM>();
        private static string productName = "";
        private static double productPrice = 0.00;
        //var logger = new LoggerConfiguration().MinimumLevel.Debug().WriteTo.File("CustomerPortalLog.txt").CreateLogger();
        public CustomerPortalController(IBL p_BL)
        {
            _BL = p_BL;
        }

        public IActionResult OpenCustomerPortal()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(CustomerVM p_custVM)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    _BL.AddCustomer(new Customer
                    {
                        Fname = p_custVM.Fname.ToUpper(),
                        Lname = p_custVM.Lname.ToUpper(),
                        Address = p_custVM.Address.ToUpper(),
                        City = p_custVM.City.ToUpper(),
                        State = p_custVM.State.ToUpper(),
                        Email = p_custVM.Email,
                        Phone = p_custVM.Phone
                    }
                    );

                    return RedirectToAction(nameof(OpenCustomerPortal));
                }
            }
            catch (Exception)
            {
                Log.Information("User Fail To Register - Incorrect RegEx");
                ViewBag.Error = "Missing/Invalid Input --- Try Again";
                return View();
            }

            Log.Information("User Fail To Register");
            ViewBag.Error = "Missing/Invalid Input --- Try Again";
            return View();
        }

        public IActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignIn(string p_fname, string p_email)
        {
            try
            {
                CustomerVM theCust = new CustomerVM();
                List<Customer> listOfSearchedCustomers = _BL.SearchCustomers("fname", p_fname.ToUpper());
                bool flag = false;
                if(listOfSearchedCustomers.Count > 0)
                {
                    foreach (Customer c in listOfSearchedCustomers)
                    {
                        if(c.Email == p_email)
                        {
                            theCust = new CustomerVM(c);
                            flag = true;
                        }
                    }

                    if(flag)
                    {
                        TempData["fName"] = theCust.Fname;
                        TempData["customerId"] = theCust.Id;

                        return RedirectToAction("SignInOption");
                    }
                }
            }
            catch (Exception)
            {
                ViewBag.Error = "DB Not Working";
                return View();
            }

            Log.Information("User Fail To Log In");
            ViewBag.Error = ViewBag.Error = "Customer Not Found";
            return View();
        }

        public IActionResult SignInOption()
        {
            return View();
        }

        

        public IActionResult FindAStore()
        {
            try
            {
                shoppingCart.Clear();
                return View(
                    _BL.GetAllStoreFronts()
                    .Select(sf => new StoreFrontVM(sf))
                    .ToList()
                );

            }
            catch (Exception)
            {
                shoppingCart.Clear();
                return View(nameof(SignInOption));
            }

        }

        public IActionResult DisplayAStoreInventory(int p_sfId)
        {
            try
            {
                TempData["sfId"] = p_sfId;
                ViewBag.Name = _BL.GetAStore(p_sfId).Name;
                List<Inventory> theStoreInventory = _BL.GetAStoreInventory(p_sfId);
                List<Product> listOfProducts = _BL.GetAllProducts();
                List<TheStoreInventoryVM> listOfTheStoreInventoryVM = new List<TheStoreInventoryVM>();
                foreach(Inventory inv in theStoreInventory)
                {
                    TheStoreInventoryVM inventory = new TheStoreInventoryVM();
                    inventory.Id = inv.Id;
                    inventory.StoreFrontId = inv.StoreFrontId;
                    inventory.Quantity = inv.Quantity;
                    foreach(Product p in listOfProducts)
                    {
                        if(inv.ProductId == p.Id)
                        {
                            inventory.ProductId = p.Id;
                            inventory.ProductName = p.Name;
                            inventory.ProductPrice = p.Price;
                        }
                    }
                    listOfTheStoreInventoryVM.Add(inventory);
                }
                return View(listOfTheStoreInventoryVM);

            }
            catch (Exception)
            {
                Log.Information("Fail To Display A Store Inventory");
                return View(nameof(SignInOption));
            }
        }

        public IActionResult CreateQuantity(TheStoreInventoryVM p_theStoreInventoryVM)
        {
            TempData["inventoryId"] = p_theStoreInventoryVM.Id;
            TempData["productId"] = p_theStoreInventoryVM.ProductId;
            productName = p_theStoreInventoryVM.ProductName;
            productPrice = p_theStoreInventoryVM.ProductPrice;
            return View(p_theStoreInventoryVM);
        }

        public IActionResult AddToCart(int p_quantity)
        {
            int sfId = (int)TempData["sfId"];
            LineItemVM liVM = new LineItemVM();
            liVM.CustomerId = (int)TempData["customerId"];
            liVM.StoreFrontId = sfId;
            liVM.InventoryId = (int)TempData["inventoryId"];
            liVM.ProductId = (int)TempData["productId"];
            liVM.ProductPrice = productPrice;
            liVM.ProductName = productName;
            liVM.Quantity = p_quantity;
            TempData.Keep("customerId");
            TempData.Keep("sfId");
            TempData.Keep("inventoryId");
            TempData.Keep("productId");
            TempData.Keep("productPrice");
            TempData.Keep("productName");
            shoppingCart.Add(liVM);
            return RedirectToAction("ViewCart");
        }

        public IActionResult ViewCart()
        {
            return View(shoppingCart);
        }

        public IActionResult EmptyCart()
        {
            shoppingCart.Clear();
            return View(nameof(ViewCart));
        }

        public IActionResult CheckOut()
        {
            //calculate cart total
            double total = 0.0;
            foreach(LineItemVM liVM in shoppingCart)
            {
                total += liVM.ProductPrice * liVM.Quantity;
            }

            //Create a new order and write to DB
            Order newOrder = new Order();
            newOrder.CustomerId = (int)TempData["customerId"];
            newOrder.StoreFrontId = (int)TempData["sfId"];
            newOrder.TotalPrice = total;
            newOrder.Date = DateTime.Now;
            newOrder = _BL.AddAnOrder(newOrder);

            //Create lineItems in the cart and write to DB
            foreach (LineItemVM liVM in shoppingCart)
            {
                LineItem li = new LineItem();
                li.OrderId = newOrder.Id;
                li.ProductId = liVM.ProductId;
                li.Quantity = liVM.Quantity;
                li = _BL.AddALineItem(li);
            }

            //Update the store inventory and write to DB
            foreach (LineItemVM liVM in shoppingCart)
            {
                _BL.UpdateInventoryQuantity(liVM.InventoryId, liVM.Quantity);
            }


            TempData.Keep("customerId");
            TempData.Keep("sfId");

            List<LineItemVM> receipt = new List<LineItemVM>(shoppingCart);
            shoppingCart.Clear();
            return View(receipt);
        }

        public IActionResult ViewOrderHistory(string sortOrder)
        {
            try
            {
                int customerId = (int)TempData["customerId"];
                TempData.Keep("customerId");

                ViewBag.DateSortParm = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
                ViewBag.PriceSortParm = sortOrder == "price" ? "price_desc" : "price";
                IEnumerable<OrderVM> listOfCustomerOrders = _BL.GetACustomerOrders(customerId).Select(order => new OrderVM(order)).ToList();

                switch (sortOrder)
                {
                    case "price":
                        listOfCustomerOrders = listOfCustomerOrders.OrderBy(o => o.TotalPrice);
                        break;
                    case "price_desc":
                        listOfCustomerOrders = listOfCustomerOrders.OrderByDescending(o => o.TotalPrice);
                        break;

                    case "date_desc":
                        listOfCustomerOrders = listOfCustomerOrders.OrderByDescending(o => o.Date);
                        break;
                    default:
                        listOfCustomerOrders = listOfCustomerOrders.OrderBy(o => o.Date);
                        break;
                }

                return View(listOfCustomerOrders);
            }
            catch (Exception)
            {
                Log.Information("Fail To Sort");
                return View(nameof(SignInOption));
            }
        }

WebUI/Views/CustomerPortal/CheckOut.cshtml
@model IEnumerable<LineItemVM>
@{ 
    double total = 0.0;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1 style="text-align:center;">Order Submitted Succesfully</h1>

    <h2>Order Detail:</h2>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Product Price</th>
                <th>Purchased Quantity</th>
                <th>Line Totals</th>

            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ProductName</td>
                        <td>@item.ProductPrice.ToString("C")</td>
                        <td>@item.Quantity</td>
                        @{
                            double subTotal = item.ProductPrice * item.Quantity;
                            total += subTotal;
                        }
                        <td>@subTotal.ToString("C")</td>

                    </tr>
                }
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">Total</td>
                <td>@total.ToString("C")</td>
            </tr>
        </tfoot>
    </table>

    <a asp-controller="CustomerPortal" asp-action="SignInOption" class="btn btn-success" style="position:relative; top:10px; width:77px;">Back</a>
</body>
</html>

WebUI/Views/CustomerPortal/CreateQuantity.cshtml
@model TheStoreInventoryVM
@{ 
    int sfId = (int)TempData["sfId"];
    TempData.Keep("sfId");
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Product Price</th>
                <th>Available Quantity</th>

            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.ProductName</td>
                <td>@Model.ProductPrice.ToString("C")</td>
                <td>@Model.Quantity</td>
            </tr>
        </tbody>
    </table>

    <form asp-action="AddToCart">

        <div class="mb-3">
            <label class="form-label">Quantity</label>
            <input name="p_quantity" type="number" class="form-control" min="0" max="@Model.Quantity">
        </div>

        <button type="submit" class="btn btn-primary">Add To Cart</button>
    </form>


    @Html.ActionLink("Back", "DisplayAStoreInventory", new { p_sfId = Model.StoreFrontId }, new { @style = "color:white; position:relative; top:10px; width:77px;", @class = "btn btn-danger" })

</body>
</html>

WebUI/Views/CustomerPortal/DisplayAStoreInventory.cshtml
@model IEnumerable<TheStoreInventoryVM>
@*@{ 
    List<TheStoreInventoryVM> availableProductId = new List<TheStoreInventoryVM>();
    int maxQuantity = 0;
    double productPrice = 0.00;
}*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>Store @ViewBag.Name's Inventory</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                @*<th>Product Id</th>*@
                <th>Product Name</th>
                <th>Product Price</th>
                <th>Available Quantity</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @*<td>@Html.DisplayFor(modelItem => item.ProductId)</td>*@
                    <td>@Html.DisplayFor(modelItem => item.ProductName)</td>
                    <td>$@Html.DisplayFor(modelItem => item.ProductPrice)</td>
                    <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                    <td>
                        @Html.ActionLink("Purchase", "CreateQuantity", item, new { @style = "color:white", @class = "btn btn-secondary" })
                    </td>
                </tr>

            }
        </tbody>
    </table>


    <a asp-controller="CustomerPortal" asp-action="FindAStore" class="btn btn-danger" style="position:relative; top:10px;">Empty Cart & Select Another Store</a>

    <a asp-controller="CustomerPortal" asp-action="ViewCart" class="btn btn-primary" style="position:relative; top:10px;">ViewCart</a>
</body>
</html>

WebUI/Views/CustomerPortal/FindAStore.cshtml
@model IEnumerable<StoreFrontVM>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>List Of Stores</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Store Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.Address)</td>
                    <td>@Html.DisplayFor(modelItem => item.City)</td>
                    <td>@Html.DisplayFor(modelItem => item.State)</td>
                    <td>
                        @Html.ActionLink("Select", "DisplayAStoreInventory", new { p_sfId = item.Id }, new { @style = "color:white", @class = "btn btn-secondary" })
                    </td>
                </tr>            
             }
        </tbody>
    </table>
    <a asp-controller="CustomerPortal" asp-action="SignInOption" class="btn btn-danger" style="position:relative; top:10px; width:77px;">Back</a>
</body>
</html>

WebUI/Views/CustomerPortal/OpenCustomerPortal.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <div class="text-center">
        <h1>Welcome To Customer Portal</h1>
    </div>

    <table>
        <tbody>
            <tr>
                <td>
                    <a type="button" class="btn btn-secondary btn-lg" asp-controller="CustomerPortal" asp-action="Register">Register</a>
                </td>
            </tr>
            <tr>
                <td>
                    <a type="button" class="btn btn-secondary btn-lg" asp-controller="CustomerPortal" asp-action="SignIn">Sign In</a>
                </td>
            </tr>
        </tbody>
    </table>
</body>
</html>

WebUI/Views/CustomerPortal/Register.cshtml
@model WebUI.Models.CustomerVM
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>Register</h1>

    <div>
        <form asp-action="Register">
            @{ if (ViewBag.Error != null)
                {
                    <div class="mb-3" style="color:red">@ViewBag.Error</div>
                } 
            }
            <div class="mb-3">
                <label asp-for="Fname" class="form-label">First Name</label>
                <input asp-for="Fname" type="text" class="form-control">
                <span asp-validation-for="Fname" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Lname" class="form-label">Last Name</label>
                <input asp-for="Lname" type="text" class="form-control">
                <span asp-validation-for="Lname" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Address" class="form-label">Address</label>
                <input asp-for="Address" type="text" class="form-control">
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="City" class="form-label">City</label>
                <input asp-for="City" type="text" class="form-control">
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="State" class="form-label">State</label>
                <input asp-for="State" type="text" class="form-control">
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input asp-for="Email" type="text" class="form-control">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Phone" class="form-label">Phone</label>
                <input asp-for="Phone" type="number" min="0" class="form-control">
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <a asp-controller="CustomerPortal" asp-action="OpenCustomerPortal" class="btn btn-danger" style="position:relative; top:10px; width:77px;">Back</a>
</body>
</html>

WebUI/Views/CustomerPortal/SignIn.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>Sign In</h1>

    <form asp-action="SignIn">
        @{ 
        if (ViewBag.Error != null)
        {
            <div class="mb-3" style="color:red">@ViewBag.Error</div> 
        } 
        }
        <div class="mb-3">
            <label class="form-label">First Name</label>
            <input name="p_fname" type="text" class="form-control" required>

        </div>

        <div class="mb-3">
            <label class="form-label">Email</label>
            <input name="p_email" type="text" class="form-control" required>
        </div>

        <button type="submit" class="btn btn-primary">Sign In</button>
    </form>
    <a asp-controller="CustomerPortal" asp-action="OpenCustomerPortal" class="btn btn-danger" style="position:relative; top:10px; width:74.5px;">Back</a>
    

</body>
</html>

WebUI/Views/CustomerPortal/SignInOption.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>Welcome @TempData["fName"], </h1>
    @{
        TempData.Keep("fName");
    }
    <table>
        <tbody>
            <tr>
                <td>
                    <a type="button" class="btn btn-secondary btn-lg" asp-controller="CustomerPortal" asp-action="FindAStore">Place Orders</a>
                </td>
            </tr>
            <tr>
                <td>
                    <a type="button" class="btn btn-secondary btn-lg" asp-controller="CustomerPortal" asp-action="ViewOrderHistory">View Order History</a>
                </td>
            </tr>
            <tr>
                <td>
                    <a type="button" class="btn btn-secondary btn-lg" asp-controller="CustomerPortal" asp-action="OpenCustomerPortal">Sign Out</a>
                </td>
            </tr>
        </tbody>
    </table>
</body>
</html>

WebUI/Views/CustomerPortal/ViewCart.cshtml
@model IEnumerable<LineItemVM>
@{ 
    double total = 0.0;
    int sfId = (int)TempData["sfId"];
    TempData.Keep("sfId");
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Product Price</th>
                <th>Purchased Quantity</th>
                <th>Line Totals</th>

            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ProductName</td>
                        <td>@item.ProductPrice.ToString("C")</td>
                        <td>@item.Quantity</td>
                        @{
                            double subTotal = item.ProductPrice * item.Quantity;
                            total += subTotal;
                        }
                        <td>@subTotal.ToString("C")</td>

                    </tr>
                }
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">Total</td>
                <td>@total.ToString("C")</td>
            </tr>
        </tfoot>
    </table>

    @Html.ActionLink("Add More Products", "DisplayAStoreInventory", new { p_sfId = sfId }, new { @style = "color:white; position:relative; top:10px;", @class = "btn btn-primary" })
    <a asp-controller="CustomerPortal" asp-action="EmptyCart" class="btn btn-danger" style="position:relative; top:10px;">Empty Cart</a>
    @if (Model != null)
    {
        @*@Html.ActionLink("Check Out", "CheckOut", Model, new { @style = "color:white; position:relative; top:10px;", @class = "btn btn-success" })*@
        <a asp-controller="CustomerPortal" asp-action="CheckOut" class="btn btn-success" style="position:relative; top:10px;">CheckOut</a>
    }
</body>
</html>

WebUI/Views/CustomerPortal/ViewOrderDetail.cshtml
@model IEnumerable<LineItemVM>
@{
    double total = 0.0;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>Order Detail:</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Product Price</th>
                <th>Purchased Quantity</th>
                <th>Line Totals</th>

            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ProductName</td>
                        <td>@item.ProductPrice.ToString("C")</td>
                        <td>@item.Quantity</td>
                        @{
                            double subTotal = item.ProductPrice * item.Quantity;
                            total += subTotal;
                        }
                        <td>@subTotal.ToString("C")</td>

                    </tr>
                }
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">Total</td>
                <td>@total.ToString("C")</td>
            </tr>
        </tfoot>
    </table>

    <a asp-controller="CustomerPortal" asp-action="ViewOrderHistory" class="btn btn-danger" style="position:relative; top:10px; width:77px;">Back</a>
</body>
</html>

WebUI/Views/CustomerPortal/ViewOrderHistory.cshtml
@model IEnumerable<OrderVM>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1 style="text-align:center;">Order History</h1>

    @{ if (Model.Count() > 0)
        {
            <table class="table table-striped">
                <thead>
                        <tr>
                            <th>Order Id</th>
                            <th>Store Front Id</th>
                            <th>@Html.ActionLink("Total Price", "ViewOrderHistory", new { sortOrder = ViewBag.PriceSortParm })</th>
                            <th>@Html.ActionLink("Date of Purchase", "ViewOrderHistory", new { sortOrder = ViewBag.DateSortParm })</th>
                        </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.StoreFrontId</td>
                        <td>@item.TotalPrice.ToString("C")</td>
                        <td>@item.Date</td>
                        <td>
                            @Html.ActionLink("Detail", "ViewOrderDetail", new { p_orderId = item.Id }, new { @style = "color:white", @class = "btn btn-secondary" })
                        </td>
                    </tr>
                    }

                </tbody>
            </table>
        }
        else
        {
            <h2>Customer Has No Order History</h2>
        }
    }
    <a asp-controller="CustomerPortal" asp-action="SignInOption" class="btn btn-danger" style="position:relative; top:10px; width:77px;">Back</a>
</body>
</html>